export interface DocEntry {
  signature: string;
  description: string;
  example?: string;
  /** Second, more advanced usage example. */
  example2?: string;
  /** Brief note on the most common mistake with this directive. */
  commonErrors?: string;
  /** Link to the relevant section of the GNU documentation. */
  docUrl?: string;
}

// ── Bison Directives ──

export const bisonDirectiveDocs: Map<string, DocEntry> = new Map([
  ['%token', {
    signature: '%token [<type>] NAME ["alias"] [value]',
    description: 'Declares one or more terminal symbols (tokens). The optional `<type>` assigns a semantic value type; `"alias"` provides a human-readable name for error messages; `value` pins the token to a specific integer.',
    example: '%token <int> INT "integer"\n%token PLUS "+" MINUS "-"',
    example2: '// Full C++ variant-mode setup with constructor tokens\n%define api.token.constructor\n%define api.value.type variant\n%token <int>         INT     "integer"\n%token <std::string> STRING  "string literal"\n%token               END   0 "end of file"',
    commonErrors: 'Declaring a token with an alias here but using it as a raw string `"+"` elsewhere — pick one form and be consistent. Also, token names must be ALL_CAPS by convention but Bison does not enforce this.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Token-Decl',
  }],
  ['%type', {
    signature: '%type <type> nonterminal ...',
    description: 'Declares the semantic value type for one or more nonterminal symbols. Required for all non-terminals when using `%define api.value.type variant`.',
    example: '%type <ast::Exp*>       exp\n%type <ast::ChunkList*> chunks',
    example2: '// Group multiple non-terminals sharing the same type\n%type <ast::Exp*>  exp addexp mulexp unaryexp\n%type <ast::Decl*> vardec fundec tydec',
    commonErrors: 'Forgetting to declare a non-terminal used in a rule when `api.value.type variant` is set causes a cryptic compile error — declare every non-terminal that carries a value.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Type-Decl',
  }],
  ['%nterm', {
    signature: '%nterm <type> nonterminal ...',
    description: 'Synonym for `%type`. Declares the semantic value type for nonterminal symbols. Preferred in modern grammars for clarity.',
    example: '%nterm <ast::Exp*> exp',
    example2: '%nterm <ast::Stm*>  stm ifstm whilestm\n%nterm <ast::Exp*>  exp lvalue',
    commonErrors: 'Mixing `%nterm` and `%type` declarations for the same symbol — pick one style per grammar.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Type-Decl',
  }],
  ['%define', {
    signature: '%define variable value',
    description: 'Sets a Bison configuration variable. Controls parser behavior, API style, namespace, error reporting, and more. The value may be bare, quoted, or braced depending on the variable.',
    example: '%define api.value.type variant\n%define api.namespace {parse}',
    example2: '// Full modern C++ parser configuration\n%define api.token.constructor\n%define api.value.type    variant\n%define api.token.prefix  {TOK_}\n%define api.namespace     {parse}\n%define api.parser.class  {parser}\n%define parse.error       detailed\n%define parse.lac         full',
    commonErrors: 'Using `%define api.value.type variant` without also adding `%define api.token.constructor` leads to implicit conversions and confusing type errors at the call site.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['%code', {
    signature: '%code [qualifier] { ... }',
    description: 'Inserts verbatim C/C++ code into specific locations in the generated files.\n- *(no qualifier)*: after YYSTYPE/YYLTYPE definitions in the implementation\n- `requires`: before YYSTYPE — put `#include` of types used in `%type`/`%token` here\n- `provides`: after YYSTYPE in the generated header — export declarations\n- `top`: very top of the implementation file — put `#include` of system headers here',
    example: '%code requires {\n  #include "ast/exp.hh"\n  #include "ast/stm.hh"\n}',
    example2: '%code top {\n  // Include before anything Bison generates\n  #include <config.h>\n}\n%code requires {\n  #include "parse/location.hh"\n  class TigerDriver;\n}\n%code {\n  #include "parse/driver.hh"\n  static yy::parser::symbol_type yylex(TigerDriver& drv);\n}',
    commonErrors: '`%code requires` runs before YYSTYPE — forward-declaring a type here then defining it in plain `%code` causes the parser header to see only the forward declaration.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#g_t_0025code-Summary',
  }],
  ['%left', {
    signature: '%left symbol ...',
    description: 'Declares tokens as **left-associative** at a given precedence level. Tokens on the same line share the same level; lines declared later have **higher** precedence.',
    example: '%left  "+" "-"\n%left  "*" "/"',
    example2: '// Classic expression precedence table (lowest → highest)\n%left     "or"\n%left     "and"\n%nonassoc "not"\n%nonassoc "=" "<>" "<" "<=" ">" ">="\n%left     "+" "-"\n%left     "*" "/"\n%precedence UMINUS',
    commonErrors: 'Declaring `%left "+" "-"` on separate lines gives them **different** precedence, which is almost never desired — put all same-level operators on one line.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Precedence-Decl',
  }],
  ['%right', {
    signature: '%right symbol ...',
    description: 'Declares tokens as **right-associative** at a given precedence level. Useful for exponentiation operators and right-recursive constructs like assignment.',
    example: '%right "^"\n%right "=" "+=" "-="',
    example2: '// Combining with %left for a full expression table\n%left  "+" "-"\n%left  "*" "/"\n%right "^"       // higher precedence, right-associative\n%right UMINUS    // unary minus, highest',
    commonErrors: 'Using `%right` for a normally left-associative operator like `-` silently produces wrong parse trees — double-check associativity before committing.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Precedence-Decl',
  }],
  ['%nonassoc', {
    signature: '%nonassoc symbol ...',
    description: 'Declares tokens as **non-associative**. Chaining them is a parse-time syntax error, which is the desired behavior for comparison operators.',
    example: '%nonassoc "=" "<>" "<" "<=" ">" ">="',
    example2: '// Force explicit parentheses: `a < b < c` is a syntax error\n%nonassoc CMP_OP\n%%\nexp: exp CMP_OP exp  { $$ = new CmpExp($1, $2, $3); }\n   | "(" exp ")"    { $$ = $2; }\n   ;',
    commonErrors: 'Declaring a token `%nonassoc` that also appears with `%left`/`%right` — the last declaration wins, but the conflict is confusing. Use only one associativity directive per token.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Precedence-Decl',
  }],
  ['%precedence', {
    signature: '%precedence symbol ...',
    description: 'Assigns a **precedence level** to tokens without specifying associativity. Use with `%prec` in rules to resolve shift/reduce conflicts when associativity is not meaningful.',
    example: '%precedence CHUNKS\n%precedence TYPE',
    example2: '// The classic dangling-else fix\n%precedence THEN   // lower precedence\n%precedence ELSE   // higher precedence\n%%\nstm: IF exp THEN stm          %prec THEN\n   | IF exp THEN stm ELSE stm\n   ;',
    commonErrors: 'Confusing `%precedence` with `%prec` — `%precedence` is a *declaration* (in the preamble), `%prec TOKEN` is a *rule modifier* (in the rules section).',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Precedence-Decl',
  }],
  ['%start', {
    signature: '%start symbol',
    description: 'Declares the grammar\'s start symbol. If omitted, Bison uses the left-hand side of the **first rule** as the start symbol.',
    example: '%start program',
    example2: '// Useful when the first rule is a helper rather than the root\n%start translation_unit\n%%\ntranslation_unit: declarations EOF ;\ndeclarations: /* empty */ | declarations declaration ;',
    commonErrors: 'Omitting `%start` and accidentally putting a helper rule first — the grammar silently uses the wrong entry point.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Start-Decl',
  }],
  ['%union', {
    signature: '%union { ... }',
    description: 'Defines YYSTYPE as a C `union`. Each field maps to a semantic value type referenced via `<fieldname>` in `%token`/`%type`. Prefer `%define api.value.type variant` in C++ grammars.',
    example: '%union {\n  int         ival;\n  double      dval;\n  char*       sval;\n}',
    example2: '// Full C grammar with %union\n%union {\n  int         ival;\n  double      dval;\n  char*       sval;\n  struct Node* node;\n}\n%token <ival> INT\n%token <sval> ID\n%type  <node> expr stmt',
    commonErrors: '`%union` generates a plain C `union`, so C++ objects with constructors/destructors are not safe inside it — use `%define api.value.type variant` instead.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Union-Decl',
  }],
  ['%expect', {
    signature: '%expect N',
    description: 'Tells Bison to expect **exactly N** shift/reduce conflicts. Bison reports an error if the actual count differs, ensuring accidental conflicts are noticed.',
    example: '%expect 1   // the classic dangling-else conflict',
    example2: '// If you introduce a new conflict, update the count\n// or use %verbose + check parser.output to decide\n%expect 2\n%verbose',
    commonErrors: 'Setting `%expect` to a high number to silence warnings without actually understanding the conflicts — always inspect `parser.output` first.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Expect-Decl',
  }],
  ['%expect-rr', {
    signature: '%expect-rr N',
    description: 'Declares the expected number of **reduce/reduce** conflicts. Only meaningful for GLR parsers (ordinary LALR parsers cannot have r/r conflicts and still function correctly).',
    example: '%expect-rr 0',
    example2: '%glr-parser\n%expect     0\n%expect-rr  2  // GLR forks on two ambiguous productions',
    commonErrors: 'Using `%expect-rr` without `%glr-parser` — it has no effect on a standard LALR grammar and may mask real errors.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Expect-Decl',
  }],
  ['%require', {
    signature: '%require "version"',
    description: 'Enforces a minimum Bison version. Ensures the grammar cannot be compiled with an older Bison that lacks required features.',
    example: '%require "3.8"',
    example2: '// Pair with modern features that need a specific version\n%require "3.2"   // minimum for api.token.constructor\n%define api.token.constructor',
    commonErrors: 'Forgetting `%require` when using Bison 3.x features — on a system with Bison 2.x installed, the build silently produces a broken parser.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Require-Decl',
  }],
  ['%language', {
    signature: '%language "lang"',
    description: 'Selects the target output language. Supported values: `"c"`, `"c++"`, `"d"`, `"java"`. Determines which skeleton is used when `%skeleton` is not given explicitly.',
    example: '%language "c++"',
    example2: '// Java output for a grammar-based tool\n%language "java"\n%define api.parser.class {MyParser}\n%define api.package  {com.example.parse}',
    commonErrors: 'Setting `%language "c++"` and also setting an explicit C skeleton via `%skeleton "yacc.c"` — the skeleton overrides the language.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['%skeleton', {
    signature: '%skeleton "file"',
    description: 'Selects the parser skeleton template. Common C++ skeletons: `"lalr1.cc"` (default), `"glr.cc"`, `"glr2.cc"` (modern GLR). The skeleton controls the shape of the generated code.',
    example: '%skeleton "lalr1.cc"',
    example2: '// Modern GLR C++ parser\n%require  "3.8"\n%skeleton "glr2.cc"\n%define   api.value.type variant\n%glr-parser',
    commonErrors: 'Using `%skeleton "glr.cc"` with modern `%define` variables — prefer `"glr2.cc"` (Bison ≥ 3.7) which supports the full modern API.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['%glr-parser', {
    signature: '%glr-parser',
    description: 'Requests a **GLR (Generalized LR)** parser. The parser forks its state at each reduce/reduce or shift/reduce conflict and pursues all alternatives in parallel, merging or discarding paths as parsing proceeds. Required for ambiguous grammars.',
    example: '%glr-parser',
    example2: '%require  "3.8"\n%skeleton "glr2.cc"\n%glr-parser\n%expect-rr 1   // one intentional ambiguity',
    commonErrors: 'Using `%glr-parser` on a grammar with many ambiguities without supplying merge functions — Bison will report a runtime "ambiguity" error if two surviving paths yield different semantic values.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#GLR-Parsers',
  }],
  ['%locations', {
    signature: '%locations',
    description: 'Enables **location tracking**. Every symbol gains a location (`@$`, `@1`…) automatically computed as the span of its children. Required when using `@$` or `@N` in actions.',
    example: '%locations',
    example2: '%locations\n%initial-action {\n  @$.begin.filename = @$.end.filename = &driver.filename;\n}\n%%\nexp: exp "+" exp { $$ = new AddExp($1,$3,@$); }',
    commonErrors: 'Using `@$` or `@1` in an action without `%locations` — the build fails with an undeclared identifier error.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Tracking-Locations',
  }],
  ['%defines', {
    signature: '%defines ["filename"]',
    description: 'Generates a **header file** containing token enum, YYSTYPE, and related declarations. The Flex lexer should `#include` this file to use the token constants.',
    example: '%defines "parser.hh"',
    example2: '// Bison side\n%defines "parse/parser.hh"\n// Flex side (scanner.ll)\n%top{\n  #include "parse/parser.hh"\n}',
    commonErrors: 'Not specifying a filename — Bison uses a default name that may conflict with other project files. Always be explicit.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['%debug', {
    signature: '%debug',
    description: 'Enables **parser debug tracing**. When `yydebug` (or `parser.set_debug_level(1)` in C++) is set to non-zero at runtime, the parser prints each state transition to stderr.',
    example: '%debug',
    example2: '// Enable in main for a debug build\n%debug\n// C++ usage:\nparse::parser p(driver);\np.set_debug_level(1);\np.parse();',
    commonErrors: '`%debug` only compiles in the tracing code — you must also set `yydebug = 1` (C) or `set_debug_level(1)` (C++) at runtime to actually see output.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Enabling-Traces',
  }],
  ['%param', {
    signature: '%param { type name }',
    description: 'Adds a parameter to **both** `yyparse()` and `yylex()`. Useful when both functions need access to the same driver/context object without global state.',
    example: '%param { ::parse::TigerDriver& td }',
    example2: '// Pass a driver to both parser and lexer\n%param { TigerDriver& drv }\n%%\n// In lexer (scanner.ll):\n// The lex function receives `drv` automatically',
    commonErrors: 'Using `%param` when only one of the two functions needs the argument — use `%parse-param` or `%lex-param` instead to keep signatures minimal.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Parser-Function',
  }],
  ['%parse-param', {
    signature: '%parse-param { type name }',
    description: 'Adds an extra parameter to **`yyparse()` only**. The argument is passed to the parser but not forwarded to the lexer.',
    example: '%parse-param { ::parse::Lexer& lexer }',
    example2: '%parse-param { ASTBuilder& builder }\n%parse-param { ErrorReporter& reporter }',
    commonErrors: 'Using the parameter name inside lexer actions — it is not in scope there. Use `%param` if the lexer also needs it.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Parser-Function',
  }],
  ['%lex-param', {
    signature: '%lex-param { type name }',
    description: 'Adds an extra parameter to **`yylex()` only**. The parser calls `yylex()` with this extra argument on each token request.',
    example: '%lex-param { YYSTYPE* yylval }',
    example2: '// Reentrant Flex: pass scanner state and location\n%lex-param  { yyscan_t scanner }\n%parse-param { yyscan_t scanner }',
    commonErrors: 'Forgetting to update the `yylex` prototype in the Flex file to accept the extra parameter — the generated parser will fail to compile.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Parser-Function',
  }],
  ['%printer', {
    signature: '%printer { code } <type>|symbol ...',
    description: 'Defines how to **print** a semantic value for debug traces and `%define parse.error detailed`. The code receives `$$` (the value) and `yyo` (an `std::ostream&`).',
    example: '%printer { yyo << $$; } <int> <double>',
    example2: '%printer { yyo << $$; }   <int>\n%printer { yyo << std::quoted($$); } <std::string>\n%printer { $$->dump(yyo); } <ast::Exp*>',
    commonErrors: 'Applying a `%printer` to a pointer type without checking for `nullptr` first — the printer is called during error recovery on possibly-uninitialized values.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Printer-Decl',
  }],
  ['%destructor', {
    signature: '%destructor { code } <type>|symbol ...',
    description: 'Defines cleanup code for semantic values that are **discarded** during error recovery or at end-of-parse. Use `$$` to reference the value.',
    example: '%destructor { delete $$; } <ast::Exp*>',
    example2: '// Different cleanup per type\n%destructor { delete $$;   } <ast::Node*>\n%destructor { free($$);    } <char*>\n%destructor { /* no-op */  } <int>',
    commonErrors: '`%destructor` is only called on *discarded* values, not on values that are successfully reduced — do not rely on it for normal object lifetime; use RAII.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Destructor-Decl',
  }],
  ['%empty', {
    signature: '%empty',
    description: 'Explicitly marks a rule alternative as matching the **empty string** (ε). Serves as documentation and enables Bison to warn if a supposedly-empty alternative actually contains symbols.',
    example: 'opt_semi: %empty | ";" ;',
    example2: 'args:\n  %empty            { $$ = new ArgList(); }\n| args "," exp      { $1->push($3); $$ = $1; }\n;',
    commonErrors: 'Writing a blank alternative without `%empty` — the rule still works but Bison cannot warn when you accidentally add a symbol to that branch.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Empty-Rules',
  }],
  ['%prec', {
    signature: '%prec TOKEN',
    description: 'Overrides the **precedence** of the entire rule with the precedence of the named token. Used to resolve shift/reduce conflicts that depend on context, not the rightmost terminal.',
    example: 'exp: "-" exp %prec UMINUS { $$ = -$2; }',
    example2: '// Dangling-else: give the short IF the precedence of THEN\n%precedence THEN\n%precedence ELSE\n%%\nstm: IF exp THEN stm          %prec THEN\n   | IF exp THEN stm ELSE stm\n   ;',
    commonErrors: 'Using `%prec` with a token that has no declared precedence — Bison silently ignores it, leaving the conflict unresolved.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Contextual-Precedence',
  }],
  ['%initial-action', {
    signature: '%initial-action { code }',
    description: 'Executes C/C++ code **once** immediately before the first token is shifted. Commonly used to initialize the current location with a filename.',
    example: '%initial-action {\n  @$.begin.filename = @$.end.filename = &driver.file;\n}',
    example2: '%initial-action {\n  // Initialize location to point to the input file\n  @$.begin.filename = @$.end.filename = &drv.filename;\n  // Reset error counter\n  drv.error_count = 0;\n}',
    commonErrors: '`%initial-action` runs before the first token is read — accessing `$1` or `@1` here is undefined; only the driver/context passed via `%param` is available.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Initial-Action-Decl',
  }],
  ['%verbose', {
    signature: '%verbose',
    description: 'Produces a human-readable **`.output`** file listing all parser states, conflicts, and the items in each state. Essential for understanding and resolving grammar conflicts.',
    example: '%verbose',
    example2: '// Combine with %expect to document known conflicts\n%verbose\n%expect 1   // one shift/reduce: dangling-else\n// Then inspect parser.output to confirm',
    commonErrors: 'Using `%verbose` without opening the generated `.output` file — the output is only useful if you actually read it to diagnose conflicts.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Understanding',
  }],
  ['%no-lines', {
    signature: '%no-lines',
    description: 'Suppresses **`#line` directives** in the generated parser. Compiler errors then point into the generated file rather than back to the `.y` source — useful when debugging the generated C/C++ directly.',
    example: '%no-lines',
    commonErrors: 'Using `%no-lines` during development makes it hard to correlate compile errors with `.y` source lines — only use for debugging the skeleton itself.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['%token-table', {
    signature: '%token-table',
    description: 'Generates an array `yytname[]` mapping token integer values to their name strings. Allows runtime lookup of a token\'s name from its numeric value.',
    example: '%token-table\n// Then in C: puts(yytname[token_value]);',
    example2: '// Useful for custom error messages\n%token-table\n%%\n// In yyerror:\nfprintf(stderr, "unexpected %s\\n", yytname[yychar]);',
    commonErrors: 'Token aliases (strings like `"+"`) appear in `yytname` as the alias, not the symbolic name — account for this when indexing.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['%output', {
    signature: '%output "filename"',
    description: 'Specifies the name of the **generated parser implementation file**. By default Bison derives the name from the input `.y` file.',
    example: '%output "parser.cc"',
    example2: '// Paired with %defines for full control over output names\n%output  "src/parse/parser.cc"\n%defines "src/parse/parser.hh"',
    commonErrors: 'Changing `%output` without updating the build system — the Makefile or CMakeLists.txt may still reference the old filename.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['%file-prefix', {
    signature: '%file-prefix "prefix"',
    description: 'Sets a **prefix** applied to all generated filenames. Equivalent to the `-b` command-line option. Rarely needed; prefer `%output` and `%defines` for explicit names.',
    example: '%file-prefix "parse/tiger"',
    commonErrors: 'Using both `%file-prefix` and `%output` — `%output` takes precedence for the implementation file and may produce unexpected name combinations.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
]);

// ── Bison %define Variables ──

export const bisonDefineDocs: Map<string, DocEntry> = new Map([
  ['api.value.type', {
    signature: '%define api.value.type variant|union|{SingleType}',
    description: 'Selects the semantic value type (YYSTYPE).\n- `variant` — type-safe C++ variant; each `%token`/`%type` uses its own declared type without casts\n- `union` — classic C union; unsafe with non-trivial C++ types\n- `{MyType}` — every symbol shares one fixed type (e.g., `{Node*}`)',
    example: '%define api.value.type variant',
    example2: '// Homogeneous AST where every symbol is a Node*\n%define api.value.type {ast::Node*}',
    commonErrors: '`variant` requires every non-terminal that carries a value to be declared with `%type` — missing declarations cause compile errors deep in the skeleton code.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['api.token.prefix', {
    signature: '%define api.token.prefix {PREFIX_}',
    description: 'Prepends a prefix to all token enum values. Prevents name collisions with macros or identifiers in the project.',
    example: '%define api.token.prefix {TOK_}',
    example2: '// Token PLUS becomes TOK_PLUS in generated code\n%define api.token.prefix {TOK_}\n%token PLUS MINUS MUL DIV',
    commonErrors: 'Applying a prefix without updating the Flex lexer — `return PLUS;` must become `return parser::token::TOK_PLUS;` (or use `make_PLUS()` with constructors).',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['api.token.constructor', {
    signature: '%define api.token.constructor',
    description: 'Generates `make_TOKEN(value, location)` factory functions for each token. Enables fully type-safe token creation in the Flex lexer without casts.',
    example: '%define api.token.constructor\n// Lexer: return parser::make_INT(atoi(yytext), loc);',
    example2: '// Full C++ setup with constructors\n%define api.token.constructor\n%define api.value.type variant\n%token <int> INT\n%token <std::string> ID\n// In Flex: return parser::make_INT(std::stoi(yytext), loc);',
    commonErrors: 'Forgetting to pass the location as the last argument to `make_TOKEN()` when `%locations` is enabled — the function signature has an extra `location_type` parameter.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Complete-Symbols',
  }],
  ['api.namespace', {
    signature: '%define api.namespace {name}',
    description: 'Wraps the generated parser class and token enum in a C++ namespace.',
    example: '%define api.namespace {parse}',
    example2: '// Nested namespace (C++17)\n%define api.namespace {tiger::parse}',
    commonErrors: 'Defining a namespace without updating `#include` paths and Flex `%option` settings — references like `parse::parser::token::PLUS` must match.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['api.prefix', {
    signature: '%define api.prefix {name}',
    description: 'Renames the `yy` prefix used for all generated symbols: parser class, token enum, `yylex`, `yyerror`, etc. Allows multiple parsers in one translation unit.',
    example: '%define api.prefix {tiger}',
    example2: '// Two parsers in the same project\n// grammar1.y: %define api.prefix {sql}\n// grammar2.y: %define api.prefix {json}',
    commonErrors: 'Changing the prefix without updating the Flex `%option prefix` — the lexer still exports `yylex` while the parser expects `tigerlex`.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['api.parser.class', {
    signature: '%define api.parser.class {ClassName}',
    description: 'Sets the name of the generated C++ parser class. Default is `parser`.',
    example: '%define api.parser.class {parser}',
    example2: '%define api.namespace     {tiger::parse}\n%define api.parser.class {Parser}\n// Usage: tiger::parse::Parser p(drv); p.parse();',
    commonErrors: 'Changing the class name without updating all instantiation sites in `main` and test code.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['api.filename.type', {
    signature: '%define api.filename.type {type}',
    description: 'Sets the C++ type used for the filename field inside location objects. Default is `std::string`.',
    example: '%define api.filename.type {const std::string}',
    example2: '%define api.filename.type {const std::string*}\n// Location stores a pointer instead of a copy',
    commonErrors: 'Using a raw pointer type (`const std::string*`) without ensuring the pointed-to string outlives all locations — dangling pointer bugs are silent.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['api.location.type', {
    signature: '%define api.location.type {type}',
    description: 'Replaces the default `location` struct with a custom C++ type. The custom type must be default-constructible and support the operations the skeleton uses.',
    example: '%define api.location.type {MyLocation}',
    example2: '// Use Boost source location\n%define api.location.type {boost::spirit::line_pos_iterator<It>}',
    commonErrors: 'The custom type must provide the same interface as `yy::location` (`.begin`, `.end`, `operator+=`) — missing members cause obscure template errors.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['api.value.automove', {
    signature: '%define api.value.automove',
    description: 'Automatically inserts `std::move()` when passing semantic values into rule actions. Avoids redundant copies when using `api.value.type variant`.',
    example: '%define api.value.automove',
    example2: '// Without automove:\nexp: exp "+" exp { $$ = std::move($1) + std::move($3); }\n// With automove: Bison inserts the moves automatically',
    commonErrors: 'With `automove` enabled, manually calling `std::move($1)` results in a move from an already-moved-from object — let Bison handle it or use explicit moves, not both.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Decl-Summary',
  }],
  ['parse.error', {
    signature: '%define parse.error simple|verbose|detailed|custom',
    description: 'Controls the verbosity of syntax error messages.\n- `simple`: plain `"syntax error"`\n- `verbose`: lists unexpected/expected tokens\n- `detailed` (≥ 3.6): like verbose with better formatting\n- `custom`: call your own `yyerror`/`parser::error` implementation',
    example: '%define parse.error detailed',
    example2: '// Best combination for user-facing parsers\n%define parse.error detailed\n%define parse.lac    full',
    commonErrors: '`verbose` with `parse.lac none` (the default) still produces inaccurate expected-token lists on complex grammars — always pair with `parse.lac full`.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Error-Reporting',
  }],
  ['parse.lac', {
    signature: '%define parse.lac full|none',
    description: 'Enables **Lookahead Correction** for more accurate expected-token lists in error messages.\n- `full`: simulate all possible continuations — accurate but slightly slower\n- `none`: use the LALR table directly — fast but may list tokens that would also cause an error',
    example: '%define parse.lac full',
    example2: '%define parse.error detailed\n%define parse.lac    full\n// Error: unexpected ";" — expected "+" or "*" or ")"',
    commonErrors: '`parse.lac full` has a runtime cost proportional to the number of valid lookaheads — measure on large inputs before enabling in production parsers.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#LAC',
  }],
  ['parse.trace', {
    signature: '%define parse.trace',
    description: 'Compile-time equivalent of `%debug`. Compiles tracing code into the parser; activate at runtime by setting `yydebug = 1` (C) or `set_debug_level(1)` (C++).',
    example: '%define parse.trace',
    example2: '// Guard so tracing is only compiled in debug builds\n#ifdef YYDEBUG\n  %define parse.trace\n#endif',
    commonErrors: 'Same as `%debug` — the flag must be activated at *runtime*, not just compiled in. Forgetting `set_debug_level(1)` produces no output.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Enabling-Traces',
  }],
  ['lr.type', {
    signature: '%define lr.type lalr|ielr|canonical-lr',
    description: 'Selects the LR table-construction algorithm.\n- `lalr`: default — compact tables, may have conflicts\n- `ielr`: Inadequacy-Elimination LR — fewer phantom conflicts than LALR, still compact\n- `canonical-lr`: no conflicts, but tables can be exponentially larger',
    example: '%define lr.type ielr',
    example2: '// Try ielr when lalr has phantom conflicts\n%define lr.type ielr\n%expect 0',
    commonErrors: '`canonical-lr` can produce hundreds of thousands of states for non-trivial grammars — never use it without checking the size of `parser.output` first.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#LR-Table-Construction',
  }],
  ['lr.default-reduction', {
    signature: '%define lr.default-reduction most|consistent|accepting',
    description: 'Controls when the parser applies a default reduction (reducing without peeking at the lookahead).\n- `most`: maximize default reductions (smallest tables, least-accurate early error detection)\n- `consistent`: only when all items agree\n- `accepting`: only in the accepting state',
    example: '%define lr.default-reduction consistent',
    commonErrors: '`most` defers lookahead consumption, which can make error positions appear one token late — use `consistent` or `accepting` for better error locations.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Default-Reductions',
  }],
]);

// ── Bison Semantic Values ──

export const bisonSemanticDocs: Map<string, DocEntry> = new Map([
  ['$$', {
    signature: '$$',
    description: 'The semantic value of the **left-hand side** (result) of the current rule. Assign to it in the action to set the rule\'s value. Its type is the one declared in `%type`/`%nterm` for the LHS non-terminal.',
    example: 'exp: exp "+" exp { $$ = $1 + $3; }',
    example2: '// With variant and pointer AST nodes\nexp: exp "+" exp { $$ = new BinExp("+", $1, $3, @$); }\n   | INT          { $$ = new IntExp($1, @1); }\n   ;',
    commonErrors: 'Not assigning `$$` when using `api.value.type variant` — the variant is left in an indeterminate state and may be accessed later by the parser.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Actions',
  }],
  ['$1', {
    signature: '$N',
    description: 'The semantic value of the **N-th symbol** on the right-hand side (1-indexed). The type is inferred from the `%type`/`%token` declaration of that symbol. `$0` accesses the symbol to the left of the current rule (rare).',
    example: 'exp: exp "+" exp { $$ = $1 + $3; }',
    example2: '// Using $<type>N to cast in %union grammars\nexp: exp "+" exp { $$ = $<ival>1 + $<ival>3; }\n   | ID           { $$ = lookup($<sval>1); }\n   ;',
    commonErrors: 'Using `$N` where N exceeds the number of symbols on the RHS — Bison does not always catch this statically and the result is undefined behavior.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Actions',
  }],
  ['@$', {
    signature: '@$',
    description: 'The **location** (source span) of the left-hand side of the current rule. Automatically computed as the span from the start of `@1` to the end of `@N`. Requires `%locations`.',
    example: 'exp: exp "+" exp { $$ = new BinExp($1, $3, @$); }',
    example2: '// Manually override when the span should be narrower\nexp: "(" exp ")" { $$ = $2; @$ = @2; /* exclude parens */ }',
    commonErrors: 'Using `@$` without `%locations` — produces an "undeclared identifier" compile error.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Tracking-Locations',
  }],
  ['@1', {
    signature: '@N',
    description: 'The **location** (source span) of the N-th symbol on the right-hand side. `@1.begin` is the start position, `@1.end` is the end. Requires `%locations`.',
    example: 'stm: "if" exp "then" stm { $$ = new IfStm($2, $4, @1); }',
    example2: '// Build a location spanning two specific tokens\nauto loc = yy::location(@2.begin, @4.end);\n$$ = new Slice($1, $3, loc);',
    commonErrors: 'Accessing `@N` in an action when `%locations` is not enabled — the location object does not exist and the build fails.',
    docUrl: 'https://www.gnu.org/software/bison/manual/bison.html#Tracking-Locations',
  }],
]);

// ── Flex Directives ──

export const flexDirectiveDocs: Map<string, DocEntry> = new Map([
  ['%option', {
    signature: '%option name[=value] ...',
    description: 'Sets scanner generation options. Multiple options can appear on a single line or across multiple `%option` lines — they are cumulative.',
    example: '%option noyywrap nounput noinput\n%option nodefault',
    example2: '// RE-flex scanner for Bison C++ integration\n%option noyywrap\n%option bison-complete\n%option bison-cc-parser=parser\n%option bison_cc_namespace=parse\n%option bison-locations\n%option namespace=parse\n%option lexer=Lexer\n%option lex=lex\n%option params="::parse::TigerDriver& td"',
    commonErrors: 'Unknown option names are silently ignored by classic Flex — use `%option nodefault` and check for warnings to catch typos.',
    docUrl: 'https://westes.github.io/flex/manual/Scanner-Options.html',
  }],
  ['%x', {
    signature: '%x STATE1 STATE2 ...',
    description: 'Declares **exclusive** start conditions. When active, *only* rules explicitly tagged `<STATE>` are considered — untagged rules are ignored. Ideal for lexing string literals, block comments, etc.',
    example: '%x SC_COMMENT SC_STRING',
    example2: '// Nested block comment using exclusive SC\n%x SC_BLOCK_COMMENT\n%%\n"/*"                   { BEGIN(SC_BLOCK_COMMENT); }\n<SC_BLOCK_COMMENT>"*/" { BEGIN(INITIAL); }\n<SC_BLOCK_COMMENT>.    { /* ignore */ }\n<SC_BLOCK_COMMENT>\\n   { /* ignore */ }',
    commonErrors: 'Declaring a state with `%x` but forgetting to add a `<STATE><<EOF>>` rule — the scanner hangs at end-of-file when the state is still active.',
    docUrl: 'https://westes.github.io/flex/manual/Start-Conditions.html',
  }],
  ['%s', {
    signature: '%s STATE1 STATE2 ...',
    description: 'Declares **inclusive** start conditions. When active, both tagged rules and untagged rules are considered. Use when you need a slight variation of the default scanning mode.',
    example: '%s SC_INDENTED',
    example2: '// Inclusive SC to track indentation without disabling other rules\n%s SC_HEREDOC\n%%\n<SC_HEREDOC>[^\\n]+ { /* accumulate */ }\n[a-z]+             { return ID; } // still active in SC_HEREDOC',
    commonErrors: 'Using `%s` when `%x` was intended — inclusive states keep all default rules active, which can cause unexpected matches.',
    docUrl: 'https://westes.github.io/flex/manual/Start-Conditions.html',
  }],
  ['%top', {
    signature: '%top { code }',
    description: 'Inserts verbatim code at the **very top** of the generated scanner file, before any Flex-generated declarations. Use for `#include` directives that must precede the scanner headers.',
    example: '%top{\n  #include <string>\n  #include "parse/parser.hh"\n}',
    example2: '// Guard against multiple inclusion + early includes\n%top{\n  #pragma once\n  #include <cstdlib>\n  #include <cerrno>\n  #include "parse/parser.hh"\n  #include "parse/location.hh"\n}',
    commonErrors: 'Putting project-specific `#include` in plain `%{ %}` blocks instead of `%top{}` — the parser header must be included before Flex\'s own YYSTYPE typedef.',
    docUrl: 'https://westes.github.io/flex/manual/Code_002dblock-Format.html',
  }],
  ['%class', {
    signature: '%class { members }',
    description: '(RE-flex) Injects member variables and method declarations directly into the generated scanner class body. Essential for storing per-scan state (string buffer, comment depth, etc.).',
    example: '%class{\n  std::string string_content;\n  int comment_depth = 0;\n}',
    example2: '// Full RE-flex class with a string accumulator and error helper\n%class{\n  std::string buf_;\n  void err(const std::string& msg) { driver_.error(location(), msg); }\n}',
    commonErrors: 'Adding method *definitions* (with bodies) in `%class` — only declarations belong here; put definitions in a separate `.cc` file or use `%{ %}` after the rules section.',
    docUrl: 'https://github.com/Genivia/RE-flex',
  }],
]);

// ── Flex Option Values ──

export const flexOptionDocs: Map<string, DocEntry> = new Map([
  ['noyywrap', {
    signature: '%option noyywrap',
    description: 'Disables the yywrap() function call at end-of-file. The scanner will simply stop instead of checking for more input.',
  }],
  ['nounput', {
    signature: '%option nounput',
    description: 'Suppresses generation of the unput() function, avoiding unused function warnings.',
  }],
  ['noinput', {
    signature: '%option noinput',
    description: 'Suppresses generation of the input() function, avoiding unused function warnings.',
  }],
  ['nodefault', {
    signature: '%option nodefault',
    description: 'Makes the scanner emit an error for unmatched input instead of echoing it. Recommended for catching missing rules.',
  }],
  ['debug', {
    signature: '%option debug',
    description: 'Enables scanner debugging mode. The scanner traces its actions when the debug flag is set.',
  }],
  ['bison-complete', {
    signature: '%option bison-complete',
    description: '(RE-flex) Enables full Bison-compatible interface including make_TOKEN constructors and location tracking.',
  }],
  ['bison-cc-parser', {
    signature: '%option bison-cc-parser=ClassName',
    description: '(RE-flex) Specifies the Bison C++ parser class name for token type generation.',
    example: '%option bison-cc-parser=parser',
  }],
  ['bison_cc_namespace', {
    signature: '%option bison_cc_namespace=ns',
    description: '(RE-flex) Sets the namespace of the Bison parser class.',
    example: '%option bison_cc_namespace=parse',
  }],
  ['bison-locations', {
    signature: '%option bison-locations',
    description: '(RE-flex) Enables Bison location tracking in the scanner.',
  }],
  ['bison-bridge', {
    signature: '%option bison-bridge',
    description: 'Enables the Bison bridge interface (reentrant scanner with yylval parameter).',
  }],
  ['reentrant', {
    signature: '%option reentrant',
    description: 'Generates a reentrant (thread-safe) scanner with no global state.',
  }],
  ['lex', {
    signature: '%option lex=name',
    description: '(RE-flex) Sets the name of the scanning method.',
    example: '%option lex=lex',
  }],
  ['lexer', {
    signature: '%option lexer=ClassName',
    description: '(RE-flex) Sets the name of the generated scanner class.',
    example: '%option lexer=Lexer',
  }],
  ['namespace', {
    signature: '%option namespace=ns',
    description: '(RE-flex) Sets the namespace for the generated scanner class.',
    example: '%option namespace=parse',
  }],
  ['params', {
    signature: '%option params="declaration"',
    description: '(RE-flex) Adds extra parameters to the lex() scanning function.',
    example: '%option params="::parse::TigerDriver& td"',
  }],
  ['prefix', {
    signature: '%option prefix="name"',
    description: 'Changes the yy prefix to the specified name, allowing multiple scanners in one program.',
    example: '%option prefix="tiger"',
  }],
  ['header-file', {
    signature: '%option header-file="filename"',
    description: 'Generates a C header file with scanner declarations.',
    example: '%option header-file="scanner.hh"',
  }],
  ['outfile', {
    signature: '%option outfile="filename"',
    description: 'Sets the name of the generated scanner source file.',
  }],
  ['case-insensitive', {
    signature: '%option case-insensitive',
    description: 'Makes the scanner case-insensitive. Patterns match regardless of letter case.',
  }],
  ['yylineno', {
    signature: '%option yylineno',
    description: 'Makes the scanner maintain a line count in the variable yylineno.',
  }],
  ['stack', {
    signature: '%option stack',
    description: 'Enables start condition stacking with yy_push_state() and yy_pop_state().',
  }],
  ['8bit', {
    signature: '%option 8bit',
    description: 'Generates an 8-bit scanner (default). Recognizes full 8-bit character set.',
  }],
  ['extra-type', {
    signature: '%option extra-type="type"',
    description: 'Specifies the type of yyextra, the extra data passed to a reentrant scanner.',
    example: '%option extra-type="struct Context*"',
  }],
]);

// ── Flex Built-in Functions ──

export const flexBuiltinDocs: Map<string, DocEntry> = new Map([
  ['start', {
    signature: 'start(condition)',
    description: '(RE-flex) Switches the scanner to the specified start condition. Equivalent to `BEGIN(condition)` in classic Flex. The condition must be declared with `%x` or `%s`.',
    example: 'start(SC_COMMENT);',
    example2: '"/*"  { start(SC_BLOCK_COMMENT); }\n"\""  { buf_.clear(); start(SC_STRING); }',
    commonErrors: 'Passing an undeclared condition name — the compiler error appears in the generated file, not the `.l` file.',
    docUrl: 'https://github.com/Genivia/RE-flex',
  }],
  ['text', {
    signature: 'text()',
    description: '(RE-flex) Returns a `const char*` to the matched text buffer. Equivalent to `yytext` in classic Flex. The buffer is valid until the next call to `lex()`.',
    example: 'return parser::make_ID(std::string(text()), location());',
    example2: '// Avoid dangling pointer: copy immediately\nstd::string val(text(), size());\nreturn parser::make_STRING(val, location());',
    commonErrors: 'Storing `text()` directly as a `const char*` past the next `lex()` call — the buffer is overwritten; always copy to `std::string` if you need it later.',
    docUrl: 'https://github.com/Genivia/RE-flex',
  }],
  ['BEGIN', {
    signature: 'BEGIN(condition)',
    description: 'Switches to the named start condition immediately. The condition must be declared with `%x` (exclusive) or `%s` (inclusive). Use `BEGIN(INITIAL)` to return to the default state.',
    example: '"/*"  { BEGIN(SC_COMMENT); }',
    example2: '"\\""          { str_buf.clear(); BEGIN(SC_STRING); }\n<SC_STRING>"\\""  { BEGIN(INITIAL); return STRING; }\n<SC_STRING>\\n    { error("unterminated string"); }',
    commonErrors: 'Forgetting `BEGIN(INITIAL)` to exit a state — the scanner stays in the state after the triggering construct ends, matching the wrong rules.',
    docUrl: 'https://westes.github.io/flex/manual/Start-Conditions.html',
  }],
  ['ECHO', {
    signature: 'ECHO',
    description: 'Writes the matched text (`yytext`) to the output stream (`yyout`). This is the **default action** for any input that does not match any rule when `%option nodefault` is not set.',
    example: '.  { ECHO; } // explicit pass-through',
    example2: '// Use ECHO as a fallback in a transformation scanner\n"foo"    { fputs("bar", yyout); }\n.        { ECHO; }',
    commonErrors: 'Relying on the implicit ECHO default instead of `%option nodefault` — unmatched input silently passes through, masking missing rules.',
    docUrl: 'https://westes.github.io/flex/manual/Actions.html',
  }],
  ['REJECT', {
    signature: 'REJECT',
    description: 'Abandons the current match and tries the **next-best** matching rule. Allows multiple rules to process the same input. Significant performance penalty — avoid when alternatives exist.',
    example: '"stop"  { word_count++; REJECT; } // count "stop" then process it',
    example2: '// Count all words while still lexing tokens\n[a-z]+  { word_count++; REJECT; }\n"if"    { return IF; }\n"while" { return WHILE; }\n[a-z]+  { return ID; }',
    commonErrors: 'Using `REJECT` in a tight loop (e.g., on `.` rules) causes O(n²) scanning — profile before using.',
    docUrl: 'https://westes.github.io/flex/manual/Actions.html',
  }],
  ['yymore', {
    signature: 'yymore()',
    description: 'Tells Flex to **append** the next match to the current `yytext` rather than replacing it. Useful for multi-rule string accumulation without a separate buffer.',
    example: '<SC_STRING>[^\"]+ { yymore(); }',
    example2: '// Accumulate escape sequences\n<SC_STRING>[^\\\\\"]+ { yymore(); }\n<SC_STRING>\\\\[nt\"] { yymore(); }\n<SC_STRING>"\""     { return STRING; }',
    commonErrors: '`yymore()` grows `yytext` unboundedly — ensure an end condition is always reachable to avoid memory exhaustion.',
    docUrl: 'https://westes.github.io/flex/manual/Actions.html',
  }],
  ['yyless', {
    signature: 'yyless(n)',
    description: 'Pushes back all but the first **n** characters of the current match. The pushed-back characters will be re-scanned on the next call. Equivalent to manually using `unput()`.',
    example: '[0-9]+\\.  { yyless(yyleng - 1); return INT; } // keep the dot',
    example2: '// Recognize a two-char token but only consume one\n"==" { return EQ; }\n"=>" { yyless(1); return EQ; } // put back ">"\n"="  { return ASSIGN; }',
    commonErrors: 'Calling `yyless(0)` puts all characters back and will cause an infinite loop if the same rule matches again.',
    docUrl: 'https://westes.github.io/flex/manual/Actions.html',
  }],
  ['INITIAL', {
    signature: 'INITIAL',
    description: 'The **default start condition** (value 0). All rules without an explicit `<condition>` prefix are active in `INITIAL`. Use `BEGIN(INITIAL)` to return from any other state.',
    example: '<SC_COMMENT>"*/" { BEGIN(INITIAL); }',
    example2: '// Explicit INITIAL tagging for clarity\n<INITIAL>"/*"    { BEGIN(SC_COMMENT); }\n<INITIAL>[a-z]+  { return ID; }',
    commonErrors: 'Declaring `%x INITIAL` — `INITIAL` is predefined and cannot be redeclared; the scanner will fail to compile.',
    docUrl: 'https://westes.github.io/flex/manual/Start-Conditions.html',
  }],
  ['<<EOF>>', {
    signature: '<<EOF>>',
    description: 'Special pattern that matches **end-of-file**. The action must either return a token or call `yyterminate()`. Can be scoped with a start condition to detect unterminated constructs.',
    example: '<<EOF>>  { return END; }',
    example2: '// Detect unterminated string and block comment\n<SC_STRING><<EOF>>  { error("unterminated string literal"); yyterminate(); }\n<SC_COMMENT><<EOF>> { error("unterminated block comment"); yyterminate(); }',
    commonErrors: 'Forgetting an `<<EOF>>` rule for exclusive states — Flex calls `yywrap()` instead of running the default action, which may silently swallow the error.',
    docUrl: 'https://westes.github.io/flex/manual/EOF.html',
  }],
  // ── RE-flex method equivalents ──
  ['size', {
    signature: 'size()',
    description: '(RE-flex) Returns the length (in bytes) of the current match. Equivalent to `yyleng` in classic Flex.',
    example: 'return parser::make_STRING(std::string(text(), size()), location());',
    commonErrors: 'Using `yyleng` in RE-flex scanner code — prefer `size()` for the RE-flex C++ API.',
    docUrl: 'https://github.com/Genivia/RE-flex',
  }],
  ['lineno', {
    signature: 'lineno()',
    description: '(RE-flex) Returns the current line number (1-based). Equivalent to `yylineno` in classic Flex. Updated automatically when `%option yylineno` (or equivalent) is active.',
    example: 'std::cerr << "error at line " << lineno() << "\\n";',
    commonErrors: 'Using `yylineno` in RE-flex code — use `lineno()` instead for the RE-flex API.',
    docUrl: 'https://github.com/Genivia/RE-flex',
  }],
  ['columno', {
    signature: 'columno()',
    description: '(RE-flex) Returns the current column number (0-based) within the current line. Not available in classic Flex.',
    example: 'loc.begin.column = columno();',
    docUrl: 'https://github.com/Genivia/RE-flex',
  }],
  ['in', {
    signature: 'in()',
    description: '(RE-flex) Returns a reference to the input stream used by the scanner. Allows switching the input source programmatically.',
    example: 'in(new_stream);',
    docUrl: 'https://github.com/Genivia/RE-flex',
  }],
  ['out', {
    signature: 'out()',
    description: '(RE-flex) Returns a reference to the output stream used by the scanner (for ECHO and similar actions).',
    example: 'out() << "matched: " << text() << "\\n";',
    docUrl: 'https://github.com/Genivia/RE-flex',
  }],
]);
