name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: input
    id: vscode-version
    attributes:
      label: VS Code version
      placeholder: "e.g. 1.89.0"
    validations:
      required: true
  - type: input
    id: extension-version
    attributes:
      label: Extension version
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Include a minimal Bison/Flex file that reproduces the issue if possible.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true